### ISSUE TITLE
Missing link library

### ISSUE THREAD

**Issue by nyacat** [eshard/obfuscator-llvm#2]
Missing link library `LLVMInterpreter` in CMakeLists.txt [L:41](https://github.com/eshard/obfuscator-llvm/blob/b23ee27b9c2238dfe9c649f9a209d721b943237e/CMakeLists.txt#L41)

This results in the inability to compile.

e.g:
[Link error](https://pastebin.com/bR9ZKsFj)

Edit: change to pastebin

**Comment by PatriceBlin** [comment]
Hi @nyacat 

Which version of llvm were you building with ?

From your comment I understand using ` target_link_libraries(LLVMObfuscator LLVMSupport LLVMInterpreter)` fixed the issue for you.

Right ?

**Comment by nyacat** [comment]
https://github.com/llvm/llvm-project
branch `llvmorg-14.0.6`

**Comment by PatriceBlin** [comment]
I think the missing dependency would be LLVMCore, not LLVMInterpreter

On 14.0.6, [`isUsedOutsideOfBlock`](https://github.com/llvm/llvm-project/blob/f28c006a5895fc0e329fe15fead81e37457cb1d1/llvm/lib/IR/Instruction.cpp#L555) is define in `llvm/lib/IR/Instruction.cpp` and part of [`LLVMCore`](https://github.com/llvm/llvm-project/blob/f28c006a5895fc0e329fe15fead81e37457cb1d1/llvm/lib/IR/CMakeLists.txt#L32).
I guess the link with `LLVMInterpreter` worked because it itself [depends on `LLVMCore`](https://github.com/llvm/llvm-project/blob/f28c006a5895fc0e329fe15fead81e37457cb1d1/llvm/lib/ExecutionEngine/Interpreter/CMakeLists.txt#L11)

If possible, would you kindly test if using `target_link_libraries(LLVMObfuscator LLVMSupport LLVMCore)` fixes the link for you ?

Thanks

**Comment by nyacat** [comment]
Thanks! that was full fix for me.
